import type { Fetcher } from '@cloudflare/workers-types';
import { getRequestEvent } from '$app/server';
import { dev } from '$app/environment';
import { env as privateEnv } from '$env/dynamic/private';

export interface BackendEnv {
	PROXMOX_VPC?: Fetcher;
	PROXMOX_USE_VPC?: string;
	PROXMOX_API_URL?: string;
	PROXMOX_TOKEN_ID?: string;
	PROXMOX_TOKEN_SECRET?: string;
	SNIPPETS?: Fetcher;
	PROXMOX_SNIPPETS_USE_VPC?: string;
	PROXMOX_SNIPPETS_ENDPOINT_URL?: string;
	PROXMOX_SNIPPETS_ENDPOINT_USERNAME?: string;
	PROXMOX_SNIPPETS_ENDPOINT_PASSWORD?: string;
	PROXMOX_SNIPPETS_ENDPOINT_VERIFY_SSL?: string;
	PROXMOX_SNIPPETS_STORAGE?: string;
	PROXMOX_VM_FIREWALL_SECURITY_GROUP?: string;
}

export function getBackendEnv(): BackendEnv {
	const platformEnv = getRequestEvent().platform?.env as
		| (App.Platform['env'] & { PROXMOX_API_SECRET?: string })
		| undefined;

	if (platformEnv?.PROXMOX_API_URL) {
		return {
			PROXMOX_VPC: platformEnv.PROXMOX_VPC,
			PROXMOX_USE_VPC: platformEnv.PROXMOX_USE_VPC,
			PROXMOX_API_URL: platformEnv.PROXMOX_API_URL,
			PROXMOX_TOKEN_ID: platformEnv.PROXMOX_TOKEN_ID,
			PROXMOX_TOKEN_SECRET: platformEnv.PROXMOX_TOKEN_SECRET ?? platformEnv.PROXMOX_API_SECRET,
			SNIPPETS: platformEnv.SNIPPETS,
			PROXMOX_SNIPPETS_USE_VPC: platformEnv.PROXMOX_SNIPPETS_USE_VPC,
			PROXMOX_SNIPPETS_ENDPOINT_URL: platformEnv.PROXMOX_SNIPPETS_ENDPOINT_URL,
			PROXMOX_SNIPPETS_ENDPOINT_USERNAME: platformEnv.PROXMOX_SNIPPETS_ENDPOINT_USERNAME,
			PROXMOX_SNIPPETS_ENDPOINT_PASSWORD: platformEnv.PROXMOX_SNIPPETS_ENDPOINT_PASSWORD,
			PROXMOX_SNIPPETS_ENDPOINT_VERIFY_SSL: platformEnv.PROXMOX_SNIPPETS_ENDPOINT_VERIFY_SSL,
			PROXMOX_SNIPPETS_STORAGE: platformEnv.PROXMOX_SNIPPETS_STORAGE,
			PROXMOX_VM_FIREWALL_SECURITY_GROUP: platformEnv.PROXMOX_VM_FIREWALL_SECURITY_GROUP
		};
	}

	if (!dev) {
		throw new Error('Cloudflare bindings are unavailable on this request');
	}

	return {
		PROXMOX_USE_VPC: privateEnv.PROXMOX_USE_VPC,
		PROXMOX_API_URL: privateEnv.PROXMOX_API_URL,
		PROXMOX_TOKEN_ID: privateEnv.PROXMOX_TOKEN_ID,
		PROXMOX_TOKEN_SECRET: privateEnv.PROXMOX_TOKEN_SECRET ?? privateEnv.PROXMOX_API_SECRET,
		PROXMOX_SNIPPETS_USE_VPC: privateEnv.PROXMOX_SNIPPETS_USE_VPC,
		PROXMOX_SNIPPETS_ENDPOINT_URL: privateEnv.PROXMOX_SNIPPETS_ENDPOINT_URL,
		PROXMOX_SNIPPETS_ENDPOINT_USERNAME: privateEnv.PROXMOX_SNIPPETS_ENDPOINT_USERNAME,
		PROXMOX_SNIPPETS_ENDPOINT_PASSWORD: privateEnv.PROXMOX_SNIPPETS_ENDPOINT_PASSWORD,
		PROXMOX_SNIPPETS_ENDPOINT_VERIFY_SSL: privateEnv.PROXMOX_SNIPPETS_ENDPOINT_VERIFY_SSL,
		PROXMOX_SNIPPETS_STORAGE: privateEnv.PROXMOX_SNIPPETS_STORAGE,
		PROXMOX_VM_FIREWALL_SECURITY_GROUP: privateEnv.PROXMOX_VM_FIREWALL_SECURITY_GROUP
	};
}
